on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'rust/**'
name: PR Checks
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: cargo test
      - run: wasm-pack build --target web
      - uses: actions/upload-artifact@v4
        with:
          name: rust
          path: ${{ github.workspace }}/rust/pkg
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f ${{ github.workspace }}/backend/docker-compose.yaml up -d
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: browser-actions/setup-chrome@v1
      - uses: actions/download-artifact@v4
        with:
          name: rust
          path: ${{ github.workspace }}/rust/pkg
      - run: pnpm install
      - run: pnpm test
      



