on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: rust
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: cargo test
      - run: wasm-pack build --target web
      - uses: actions/upload-artifact@v4
        with:
          name: rust
          path: ${{ github.workspace }}/rust/pkg
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - run: docker compose -f ${{ github.workspace }}/example/docker-compose.yaml up -d
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - uses: browser-actions/setup-chrome@v1
      - uses: actions/download-artifact@v4
        with:
          name: rust
          path: ${{ github.workspace }}/rust/pkg
      - run: npm install
      - run: npm test
      



